### ISSUE TITLE
1.4.4 fails to build on OSX 10.6.8

### ISSUE THREAD

**Issue by anthonygreen** [simsong/tcpflow#71]
brew install tcpflow results in:

```
  wifipcap/wifipcap.cpp: In member function ‘const char* Wifipcap::SetFilter(const char*)’:
  wifipcap/wifipcap.cpp:1738: error: ‘PCAP_NETMASK_UNKNOWN’ was not declared in this scope
  make[1]: *** [wifipcap/wifipcap.o] Error 1
  make[1]: *** Waiting for unfinished jobs....
  make: *** [install-recursive] Error 1
```
