### ISSUE TITLE
Compile error regarding sqlite3 - sqlite3_create_function_v2

### ISSUE THREAD

**Issue by slernst** [simsong/tcpflow#83]
Get error in "be13_api/feature_recorder_sql.cpp", See Error: below.

Env: CentOS 6.5 Final, all dev/compile requirement installed.  Code did compile in ver 1.4.4.  Have performed clean, distclean to re-configure build options. make with no options.

Error:
be13_api/feature_recorder_sql.cpp: In member function ‘virtual void feature_recorder::dump_histogram_db(const histogram_def&, void_, int (_)(void_, const feature_recorder&, const histogram_def&, const std::string&, const uint64_t&)) const’:
be13_api/feature_recorder_sql.cpp:280: error: ‘sqlite3_create_function_v2’ was not declared in this scope
be13_api/feature_recorder_sql.cpp:291: error: ‘sqlite3_create_function_v2’ was not declared in this scope
make[2]: *_\* [be13_api/feature_recorder_sql.o] Error 1
