### ISSUE TITLE
Tcpflow 1.4.3 doesn't build on gcc <= 4.6

### ISSUE THREAD

**Issue by dkogan** [simsong/tcpflow#64]
Hi. I don't know if we consider this to be a bug, so you can just close this report, if this is ok. I'm seeing build problems with gcc <= 4.6. It works with gcc 4.8. Haven't tried with gcc 4.7. Here's what happens:

```
dima@shorty:~/debianstuff/tcpflow/src$ g++-4.4 -DHAVE_CONFIG_H -I. -I..  -I../src/be13_api -I../src/wifipcap -pthread -std=c++0x -c -o tcpflow.o tcpflow.cpp  
tcpflow.cpp: In member function 'inflater& inflater::operator=(const inflater&)':
tcpflow.cpp:213:   instantiated from 'void std::vector<_Tp, _Alloc>::_M_insert_aux(__gnu_cxx::__normal_iterator<typename std::_Vector_base<_Tp, _Alloc>::_Tp_a
/usr/include/c++/4.4/bits/vector.tcc:100:   instantiated from 'void std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = inflater, _Tp = inflater
/usr/include/c++/4.4/bits/stl_vector.h:747:   instantiated from 'void std::vector<_Tp, _Alloc>::push_back(_Tp&&) [with _Tp = inflater, _Alloc = std::allocator
tcpflow.cpp:264:   instantiated from here
tcpflow.cpp:213: error: non-static const member 'const std::string inflater::suffix', can't use default assignment operator
tcpflow.cpp:213: error: non-static const member 'const std::string inflater::invoc_format', can't use default assignment operator
In file included from /usr/include/c++/4.4/vector:70,
                 from be13_api/bulk_extractor_i.h:81,
                 from tcpflow.h:252,
                 from tcpflow.cpp:15:
/usr/include/c++/4.4/bits/vector.tcc: In member function 'void std::vector<_Tp, _Alloc>::_M_insert_aux(__gnu_cxx::__normal_iterator<typename std::_Vector_base
/usr/include/c++/4.4/bits/vector.tcc:314: note: synthesized method 'inflater& inflater::operator=(const inflater&)' first required here 
```
